template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "choc1276"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
